# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  secondapi:
    image: secondapi
    build:
      context: .
      dockerfile: src/Api/SecondApi/Dockerfile
    ports:
      - 5000:5000
